WebCALCI/WebCALCI/Models/Operation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebCALCI.Models
{ 
        public class Operation
        {
            public int Num1 { get; set; }
            public int Num2 { get; set; }
            public int Result { get; set; }
        }
}

WebCALCI/WebCALCI/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebCALCI.Models;

namespace WebCALCI.Controllers
{
    public class CalculatorController : Controller
    {
        public static List<Operation> operations = new List<Operation>();
        // GET: Calculator
        public ActionResult Index()
        {
            return View(operations);
        }
        public ActionResult UpdateOperations(Operation operation)
        {
            operation.Result = operation.Num1 + operation.Num2;
            operations.Add(operation);
            return View("Index", operations);
        }
    }
}

WebCALCI/WebCALCI/Views/Calculator/Index.cshtml
@using WebCALCI.Models
@model List<Operation>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" http-equiv="refresh" content="10;@Url.Action("Index", "Calculator")" />
     
    <title>Index</title>
    <style>
        input[type=text] {
            background-color: #00ffff;
            color: black;
        }
    </style>
</head>
<body>

    <h1>BRAND _NEW Web Calci </h1>
    <div>
        <form action="@Url.Action("UpdateOperations", "Calculator")" method="get">
            <table border="1">
                <tr style="background-color:#ffd800">
                    <th>Num1 </th>
                    <th> + </th>
                    <th>Num2 </th>
                    <th> = </th>
                    <th>Result </th>
                </tr>
                @foreach (Operation op in Model)
                {
                    <tr>
                        <td align="center">@op.Num1 </td>
                        <td align="center"> + </td>
                        <td align="center">@op.Num2 </td>
                        <td> = </td>
                        <td align="right">@op.Result </td>
                    </tr>
                }
                <tr>
                    <td>@Html.TextBox("Num1", null, new { @class = "form-control" })  </td>
                    <td> + </td>
                    <td>@Html.TextBox("Num2", null, new { @class = "form-control" })  </td>
                    <td> = </td>
                    <td align="center"><input type="submit" value="Add"></td>
                </tr>
            </table>
        </form>
    </div>
</body>
</html>

WebCALCI/WebCALCI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>